GET http://localhost:5000/
###
//PRODUCTS
GET http://localhost:5000/products

###
GET http://localhost:5000/products/6

###
POST http://localhost:5000/products
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "name":"Fanta 1L",
    "price":75
}

###
PATCH  http://localhost:5000/products/5
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "price":80
}
###
DELETE  http://localhost:5000/products/5
Authorization: Bearer {{$dotenv token}}

//STOCK
####
POST http://localhost:5000/stock/
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{   
    "productId":6,
    "availableQuantity":20
}

###
PATCH  http://localhost:5000/stock/4
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{   
    "availableQuantity":20
}


//SALES
###
GET http://localhost:5000/sales
###
POST http://localhost:5000/sales
content-type: application/json

{
    "quantity":1,
    "productId":4, "totalPrice":4000
}

####
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
    "username": "{{$dotenv username}}",
    "password": "{{$dotenv password}}"
}


